version: "3.9"
services:

  jupyter:
    image: jupyter/all-spark-notebook:lab-3.0.16
    container_name: jupyterlab
    ports:
      - 8889:8888
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes